name: Test SSH to EC2

on:
  workflow_dispatch:   # lets you run manually from GitHub Actions tab

jobs:
  ssh-test:
    runs-on: ubuntu-latest
    steps:
      - name: Test SSH Connection
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "✅ SSH connection successful"
            uname -a
            whoami
